#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x5F1B2A0789F12B11 (jeremie.galarneau@gmail.com)
#
Name     : babeltrace
Version  : 1.5.5
Release  : 3
URL      : http://www.efficios.com/files/babeltrace/babeltrace-1.5.5.tar.bz2
Source0  : http://www.efficios.com/files/babeltrace/babeltrace-1.5.5.tar.bz2
Source99 : http://www.efficios.com/files/babeltrace/babeltrace-1.5.5.tar.bz2.asc
Summary  : libbabeltrace provides a reader for trace files, reading mainly the
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1 MIT
Requires: babeltrace-bin
Requires: babeltrace-lib
Requires: babeltrace-doc
BuildRequires : bison
BuildRequires : elfutils-dev
BuildRequires : flex
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(uuid)
BuildRequires : popt-dev
BuildRequires : util-linux-dev

%description
BabelTrace - Trace Format Babel Tower
This project provides trace read and write libraries, as well as a trace
converter. A plugin can be created for any trace format to allow its conversion
to/from another trace format.

%package bin
Summary: bin components for the babeltrace package.
Group: Binaries

%description bin
bin components for the babeltrace package.


%package dev
Summary: dev components for the babeltrace package.
Group: Development
Requires: babeltrace-lib
Requires: babeltrace-bin
Provides: babeltrace-devel

%description dev
dev components for the babeltrace package.


%package doc
Summary: doc components for the babeltrace package.
Group: Documentation

%description doc
doc components for the babeltrace package.


%package lib
Summary: lib components for the babeltrace package.
Group: Libraries

%description lib
lib components for the babeltrace package.


%prep
%setup -q -n babeltrace-1.5.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1522156929
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1522156929
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/babeltrace
/usr/bin/babeltrace-log

%files dev
%defattr(-,root,root,-)
/usr/include/babeltrace/babeltrace.h
/usr/include/babeltrace/clock-types.h
/usr/include/babeltrace/context.h
/usr/include/babeltrace/ctf-ir/clock.h
/usr/include/babeltrace/ctf-ir/event-class.h
/usr/include/babeltrace/ctf-ir/event.h
/usr/include/babeltrace/ctf-ir/field-types.h
/usr/include/babeltrace/ctf-ir/fields.h
/usr/include/babeltrace/ctf-ir/stream-class.h
/usr/include/babeltrace/ctf-ir/utils.h
/usr/include/babeltrace/ctf-writer/clock.h
/usr/include/babeltrace/ctf-writer/event-fields.h
/usr/include/babeltrace/ctf-writer/event-types.h
/usr/include/babeltrace/ctf-writer/event.h
/usr/include/babeltrace/ctf-writer/stream-class.h
/usr/include/babeltrace/ctf-writer/stream.h
/usr/include/babeltrace/ctf-writer/writer.h
/usr/include/babeltrace/ctf/callbacks.h
/usr/include/babeltrace/ctf/events.h
/usr/include/babeltrace/ctf/iterator.h
/usr/include/babeltrace/error.h
/usr/include/babeltrace/format.h
/usr/include/babeltrace/iterator.h
/usr/include/babeltrace/list.h
/usr/include/babeltrace/trace-handle.h
/usr/lib64/libbabeltrace-ctf-metadata.so
/usr/lib64/libbabeltrace-ctf-text.so
/usr/lib64/libbabeltrace-ctf.so
/usr/lib64/libbabeltrace-dummy.so
/usr/lib64/libbabeltrace-lttng-live.so
/usr/lib64/libbabeltrace.so
/usr/lib64/pkgconfig/babeltrace-ctf.pc
/usr/lib64/pkgconfig/babeltrace.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/babeltrace/*
%doc /usr/share/man/man1/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libbabeltrace-ctf-metadata.so.1
/usr/lib64/libbabeltrace-ctf-metadata.so.1.0.0
/usr/lib64/libbabeltrace-ctf-text.so.1
/usr/lib64/libbabeltrace-ctf-text.so.1.0.0
/usr/lib64/libbabeltrace-ctf.so.1
/usr/lib64/libbabeltrace-ctf.so.1.0.0
/usr/lib64/libbabeltrace-dummy.so.1
/usr/lib64/libbabeltrace-dummy.so.1.0.0
/usr/lib64/libbabeltrace-lttng-live.so.1
/usr/lib64/libbabeltrace-lttng-live.so.1.0.0
/usr/lib64/libbabeltrace.so.1
/usr/lib64/libbabeltrace.so.1.0.0
